const constants = {
    LOAD_DEVICES: 'LOAD_DEVICES',
    FILTER_DEVICES: 'FILTER_DEVICES',
    DELETE_DEVICE: 'DELETE_DEVICE',
    ADD_DEVICE: 'ADD_DEVICE',
    EDIT_DEVICE: 'EDIT_DEVICE',
};

export default constants
